### ISSUE TITLE
Unify copper

### ISSUE THREAD

**Issue by CyricV** [CyricV/TelluraPack#5]

**Comment by CyricV** [comment]
remove tinker tin and copper from world gen, but it's still present in the form of surface gravel

**Comment by Beisa** [comment]
Isn't there a way to change other types to tinker?

**Comment by CyricV** [comment]
yeah, most barrels can do this, I think I'm going to close this and reopen later if it becomes a problem.  I want this pack to be very polished so I may have to go in and rewrite all the recipes that produce non-appropriate metals. It's a lot of effort for a little change most people wont notice, so I think I'll hold off on it for now.
